### ISSUE TITLE
[BUG] Latest MLC does not use mlcdrv.sys by default

### ISSUE THREAD

**Issue by wiredroid** [FarisR99/IMLCGui#11]
**Describe the bug**
When I run latency check I hard wall on 50ns. When I run using Admin CMD I need to use the -e0 parameter to use Windows Driver to get the correct reading of 41.*ns.

mlc --latency_matrix -e0

![image](https://user-images.githubusercontent.com/86910506/212298332-2fe4a59f-8b7b-414a-a80b-b38da2a31fdb.png)

![image](https://user-images.githubusercontent.com/86910506/212298500-4e27cf4b-55f2-459d-9163-64950d3041fc.png)

**Comment by FarisR99** [comment]
I was able to reproduce this issue last week and fix it, but haven't had the chance to test the fix.

Note that this is only an issue with MLC 3.10 and higher, v3.9a which the GUI downloads still works as expected. I'm still going to try supporting new MLC versions as they support newer CPU platforms.

**Comment by wiredroid** [comment]
Yes, version 3.9a gives me a reading of 6ns that's why I tried the to
download the latest from the Intel website.

**Comment by FarisR99** [comment]
Thanks for filing the bug report, can you please test @wiredroid and confirm it works for you with 3.10? https://github.com/FarisR99/IMLCGui/releases/tag/1.2.0-pre
The download button has also been updated to download 3.10 automatically.

**Comment by wiredroid** [comment]
Sorry Faris I'm away at the moment hopefully you can find someone else to
test this for you.

**Comment by sanyer** [comment]
@FarisR99 I never experienced this bug, but 1.2.0-pre works well and downloads 3.10.

**Comment by FarisR99** [comment]
Bumped 1.2.0-pre to 1.2.0 as I won't have time to fix anything until next weekend. Please reopen this issue if the bug is still present, thanks.
