### ISSUE TITLE
[BUG] Download button not working

### ISSUE THREAD

**Issue by swax185** [FarisR99/IMLCGui#14]
Fails to download MLC version I even tried different versions of MLC such as 3.11, 3.11a and the latest b. None of them seem to work for me. How to solve this problem?

![MLC](https://github.com/user-attachments/assets/16e68e1f-30a2-427b-ad9d-2d6efd984b88)

**Comment by FarisR99** [comment]
Thanks for flagging, will take a look tomorrow.

**Comment by swax185** [comment]
I hope you can fix it.

**Comment by FarisR99** [comment]
@swax185 Should be working now, please try the latest IMLCGui (v1.2.2). If you still see this issue, feel free to reopen or create a new issue.

**Comment by swax185** [comment]
> @swax185 Should be working now, please try the latest IMLCGui (v1.2.2). If you still see this issue, feel free to reopen or create a new issue.

It's all good now. Thank you.

![MLC](https://github.com/user-attachments/assets/a04413c6-1994-4d82-a344-da2f98ef9b83)
